### ISSUE TITLE
The "required" property is not supported ?

### ISSUE THREAD

**Issue by StefH** [cvent/json-schema-2-poco#24]
When using this **Basic example** schema on : http://json-schema.org/examples.html 

``` json
{
	"title": "Example Schema",
	"type": "object",
	"properties": {
		"firstName": {
			"type": "string"
		},
		"lastName": {
			"type": "string"
		},
		"age": {
			"description": "Age in years",
			"type": "integer",
			"minimum": 0
		}
	},
	"required": ["firstName", "lastName"]
}
```

The software generates this error:

```
2015-06-16 21:19:15.1404 [Error] Could not parse the schema: file:///c:/temp/jschema.json
Make sure your schema is compatible.Examine the stack trace below.
2015-06-16 21:19:15.1603 [Fatal] System.ArgumentException: Can not convert Array to Boolean.
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at Newtonsoft.Json.Schema.JsonSchemaBuilder.ProcessSchemaProperties(JObject schemaObject)
   at Newtonsoft.Json.Schema.JsonSchemaBuilder.BuildSchema(JToken token)
   at Newtonsoft.Json.Schema.JsonSchemaBuilder.Read(JsonReader reader)
   at Newtonsoft.Json.Schema.JsonSchema.Read(JsonReader reader, JsonSchemaResolver resolver)
   at Newtonsoft.Json.Schema.JsonSchema.Parse(String json, JsonSchemaResolver resolver)
   at Cvent.SchemaToPoco.Core.JsonSchemaResolver.ResolveSchemaHelper(Uri curr, Uri parent, String data) in C:\Users\Stef\Documents\Github\forks\json-schema-2-poco
```

**Comment by StefH** [comment]
Probably related to https://github.com/JamesNK/Newtonsoft.Json/issues/115
